// Every creature type in the Comprehensive Rules (205.3m), as listed by
// Scryfall's creature-type catalog. Multi-word and one-letter types are left
// out: the type-line parser splits on spaces, and a lone capital letter is not a
// reliable mention. Used to spot a tribe a card's rules text names
// (`deck-draft/ADR-0005`).
export const CREATURE_TYPES: readonly string[] = [
  "Advisor", "Aetherborn", "Alien", "Ally", "Andorian", "Angel", "Antelope", "Ape",
  "Archer", "Archon", "Armadillo", "Army", "Artificer", "Assassin", "Assembly-Worker",
  "Astartes", "Atog", "Aurochs", "Automaton", "Avatar", "Azra", "Badger", "Balloon",
  "Barbarian", "Bard", "Basilisk", "Bat", "Bear", "Beast", "Beaver", "Beeble", "Beholder",
  "Berserker", "Bird", "Bison", "Blinkmoth", "Boar", "Borg", "Brainiac", "Bringer",
  "Brushwagg", "C'tan", "Caitian", "Camarid", "Camel", "Capybara", "Caribou", "Carrier",
  "Cat", "Centaur", "Chicken", "Child", "Chimera", "Citizen", "Cleric", "Clown",
  "Cockatrice", "Construct", "Coward", "Coyote", "Crab", "Crocodile", "Custodes",
  "Cyberman", "Cyclops", "Dalek", "Dauthi", "Demigod", "Demon", "Deserter", "Detective",
  "Devil", "Dinosaur", "Djinn", "Doctor", "Dog", "Dragon", "Drake", "Dreadnought", "Drix",
  "Drone", "Druid", "Dryad", "Dwarf", "Echidna", "Efreet", "Egg", "Elder", "Eldrazi",
  "Elemental", "Elephant", "Elf", "Elk", "Employee", "Eternal", "Eye", "Faerie", "Ferret",
  "Fish", "Flagbearer", "Fox", "Fractal", "Frog", "Fungus", "Gamer", "Gamma", "Gargoyle",
  "Germ", "Giant", "Giraffe", "Gith", "Glimmer", "Gnoll", "Gnome", "Goat", "Goblin", "God",
  "Golem", "Gorgon", "Gorn", "Graveborn", "Gremlin", "Griffin", "Guest", "Hag", "Halfling",
  "Hamster", "Harpy", "Head", "Hedgehog", "Hellion", "Hero", "Hippo", "Hippogriff",
  "Homarid", "Homunculus", "Horror", "Horse", "Human", "Hydra", "Hyena", "Illusion", "Imp",
  "Incarnation", "Inhuman", "Inkling", "Inquisitor", "Insect", "Jackal", "Jellyfish",
  "Juggernaut", "Kangaroo", "Kavu", "Kelpien", "Kirin", "Kithkin", "Klingon", "Knight",
  "Kobold", "Kor", "Kraken", "Kree", "Lamia", "Lammasu", "Lanthanite", "Leech", "Lemur",
  "Leviathan", "Lhurgoyf", "Licid", "Lizard", "Llama", "Lobster", "Manticore", "Masticore",
  "Mercenary", "Merfolk", "Metathran", "Minion", "Minotaur", "Mite", "Mole", "Monger",
  "Mongoose", "Monk", "Monkey", "Moogle", "Moonfolk", "Mount", "Mouse", "Mutant", "Myr",
  "Mystic", "Naga", "Nautilus", "Necron", "Nephilim", "Nightmare", "Nightstalker", "Ninja",
  "Noble", "Noggle", "Nomad", "Nymph", "Octopus", "Officer", "Ogre", "Ooze", "Orb", "Orc",
  "Orgg", "Orion", "Otter", "Ouphe", "Ox", "Oyster", "Pangolin", "Peasant", "Pegasus",
  "Pentavite", "Performer", "Pest", "Phelddagrif", "Phoenix", "Phyrexian", "Pilot",
  "Pincher", "Pirate", "Plant", "Platypus", "Porcupine", "Possum", "Praetor", "Primarch",
  "Prism", "Processor", "Qu", "Rabbit", "Raccoon", "Ranger", "Rat", "Rebel", "Reflection",
  "Reveler", "Rhino", "Rigger", "Robot", "Rogue", "Rukh", "Sable", "Salamander", "Samurai",
  "Sand", "Saproling", "Satyr", "Scarecrow", "Scientist", "Scion", "Scorpion", "Scout",
  "Sculpture", "Seal", "Serf", "Serpent", "Servo", "Shade", "Shaman", "Shapeshifter",
  "Shark", "Sheep", "Shi'ar", "Siren", "Skeleton", "Skrull", "Skunk", "Slith", "Sliver",
  "Sloth", "Slug", "Snail", "Snake", "Soldier", "Soltari", "Sorcerer", "Spawn", "Specter",
  "Spellshaper", "Sphinx", "Spider", "Spike", "Spirit", "Splinter", "Sponge", "Spy",
  "Squid", "Squirrel", "Starfish", "Surrakar", "Survivor", "Symbiote", "Synth", "Talosian",
  "Teddy", "Tellarite", "Tentacle", "Tetravite", "Thalakos", "Tholian", "Thopter",
  "Thrull", "Tiefling", "Tosk", "Toy", "Treefolk", "Trilobite", "Triskelavite", "Troll",
  "Turtle", "Tyranid", "Unicorn", "Urzan", "Utrom", "Vampire", "Varmint", "Vedalken",
  "Villain", "Volver", "Vorta", "Vulcan", "Wall", "Walrus", "Warlock", "Warrior", "Weasel",
  "Weird", "Werewolf", "Whale", "Wizard", "Wolf", "Wolverine", "Wombat", "Worm", "Wraith",
  "Wurm", "Xindi", "Yeti", "Zombie", "Zubera",
];
